dotfiles sync 2026-04-07

diff --git a/dot_zsh/zshrc/functions.sh.tmpl b/dot_zsh/zshrc/functions.sh.tmpl
--- a/dot_zsh/zshrc/functions.sh.tmpl
+++ b/dot_zsh/zshrc/functions.sh.tmpl
@@ -30,7 +30,7 @@ update-dotfiles() {
                 # Pull and Push
                 # We use || true to prevent the subshell from exiting early if one repo fails
                 echo "Pulling..."
-                git pull --rebase --no-edit origin main || echo "Warning: Failed to pull $repo"
+                git pull --rebase -X theirs origin main || echo "Warning: Failed to pull $repo"
                 echo "Pushing..."
                 git push -u origin main || echo "Warning: Failed to push $repo"
                 echo ""
